Added some more debugging code to try to find whatever ails us.  Added an audit program to do real simple & cheezy audits of the obj_ptr_log's output. Grep would probably be as useful at this point :)

diff --git a/mud/grrmud/truncate_log b/mud/grrmud/truncate_log
--- a/mud/grrmud/truncate_log
+++ b/mud/grrmud/truncate_log
@@ -12,22 +12,23 @@ fi
 if [ -f ${LOG_FILE} ]
 then
 
-   echo "" >> log/ERROR.lg
-   echo "" >> log/WARN.lg
-   echo -n "***************  " >> log/ERROR.lg
-   echo -n "******************  " >> log/WARN.lg
+    grep ERROR ${LOG_FILE} > /tmp/ERROR.lg
+    if [ $? = 0 ]; then
+	echo "" >> ./log/ERROR.lg
+	echo -n "***************  " >> ./log/ERROR.lg
+	date >> log/ERROR.lg
+	cat /tmp/ERROR.lg >> ./log/ERROR.lg
+    fi
 
-   date >> log/ERROR.lg
-   date >> log/WARN.lg
+    grep WARN ${LOG_FILE} > /tmp/WARN.lg
+    if [ $? = 0 ]; then
+	echo "" >> ./log/WARN.lg
+	echo -n "******************  " >> ./log/WARN.lg
+	date >> ./log/WARN.lg
+	cat /tmp/WARN.lg >> ./log/WARN.lg
+    fi
 
-   grep ERROR ${LOG_FILE} >> log/ERROR.lg
-   grep WARN ${LOG_FILE} >> log/WARN.lg
-
-   # The logging class takes care of this kind of thing now.
-   #tail -1000 ${LOG_FILE} > /tmp/logfile.tmp
-   #mv /tmp/logfile.tmp ${LOG_FILE}
-
-   exit 0
+    exit 0
 
 else
 
